name: edu

services:
  server:
    build:
      context: .
    ports:
      - "9000:80"
    depends_on:
      db:
        condition: service_healthy
      log:
        condition: service_started
    post_start:
      - command: /var/www/html/bin/console make:migration
      - command: /var/www/html/bin/console doctrine:migration:migrate
      - command: /var/www/html/bin/console doctrine:fixtures:load --no-interaction
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - database_data:/var/lib/mysql:rw
      - ./docker/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: edu
      MYSQL_USER: edu
      MYSQL_PASSWORD: edu-password
    expose:
      - 3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  log:
    image: redis:7.0

volumes:
  database_data:
