name: edu

services:
  web:
    build:
      context: .
    ports:
      - "9000:80"
    depends_on:
      db:
        condition: service_healthy
      log:
        condition: service_started
    develop:
      watch:
        - action: sync
          path: ./src
          target: /var/www/html/src
        - action: sync
          path: ./templates
          target: /var/www/html/templates
    post_start:
      - command: /var/www/html/docker/init-script.sh

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - database_data:/var/lib/mysql:rw
      - ./docker/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: edu
      MYSQL_USER: edu
      MYSQL_PASSWORD: edu-password
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  log:
    image: redis:7.0
    expose:
      - 6379

volumes:
  database_data:
